#Find the second-highest number in a List
#Find all duplicate element/number in a List
#Count the frequency of character in a string
#Reverse each word in a sentence
#Print 1 to 10 numbers using 2 thread
