#Find the second-highest number in a List
#Find all duplicate element/number in a List
#Count the frequency of character in a string
#Reverse each word in a sentence
#Print 1 to 10 numbers using 2 thread
#Print Fibonacci series up to 20 terms
#Write a program swapping variable a = 30, b = 80
#Count employees and sort them by salary in descending order and then name alphabetically Using Java 8 stream
